"""empty message

Revision ID: 12fd06ea6c67
Revises: fb2940f8b100
Create Date: 2016-08-26 01:15:24.605974

"""

# revision identifiers, used by Alembic.
revision = '12fd06ea6c67'
down_revision = 'fb2940f8b100'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('link', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'link')
    ### end Alembic commands ###
