"""empty message

Revision ID: 21b9ad6ba5c4
Revises: 6a6c2cb96080
Create Date: 2016-10-10 20:28:02.091901

"""

# revision identifiers, used by Alembic.
revision = '21b9ad6ba5c4'
down_revision = '6a6c2cb96080'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('username', sa.String(length=40), nullable=True))
    op.drop_column('seeds', 'original_seeder_id')
    op.drop_column('seeds', 'seeder_name')
    op.add_column('users', sa.Column('apple_vendor_id', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('real_name', sa.String(length=40), nullable=True))
    op.drop_constraint(u'users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['apple_vendor_id'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_initial')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_initial', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_username_key', 'users', ['username'])
    op.drop_column('users', 'real_name')
    op.drop_column('users', 'apple_vendor_id')
    op.add_column('seeds', sa.Column('seeder_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('original_seeder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('seeds', 'username')
    ### end Alembic commands ###
