"""empty message

Revision ID: 27c68b634aca
Revises: d579e2644764
Create Date: 2016-10-25 23:19:52.744976

"""

# revision identifiers, used by Alembic.
revision = '27c68b634aca'
down_revision = 'd579e2644764'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql
from sqlalchemy import Integer

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upvoted_seeds', postgresql.ARRAY(Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upvoted_seeds')
    ### end Alembic commands ###
