"""empty message

Revision ID: 58dc3c57dab8
Revises: 12fd06ea6c67
Create Date: 2016-08-26 18:10:58.805451

"""

# revision identifiers, used by Alembic.
revision = '58dc3c57dab8'
down_revision = '12fd06ea6c67'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('original_seeder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seeds', 'users', ['original_seeder_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'original_seeder_id')
    ### end Alembic commands ###
