"""empty message

Revision ID: 6a6c2cb96080
Revises: 9e86e23c84af
Create Date: 2016-09-13 01:19:03.598692

"""

# revision identifiers, used by Alembic.
revision = '6a6c2cb96080'
down_revision = '9e86e23c84af'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('seeds', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('seeds', sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326), nullable=True))
    op.add_column('seeds', sa.Column('seeder_name', sa.String(), nullable=True))
    op.add_column('seeds', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_constraint(u'seeds_circle_id_fkey', 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'circle_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('circle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'seeds_circle_id_fkey', 'seeds', 'circles', ['circle_id'], ['id'])
    op.drop_column('seeds', 'timestamp')
    op.drop_column('seeds', 'seeder_name')
    op.drop_column('seeds', 'point')
    op.drop_column('seeds', 'lng')
    op.drop_column('seeds', 'lat')
    ### end Alembic commands ###
