"""empty message

Revision ID: 9e86e23c84af
Revises: 58dc3c57dab8
Create Date: 2016-08-26 18:34:24.342421

"""

# revision identifiers, used by Alembic.
revision = '9e86e23c84af'
down_revision = '58dc3c57dab8'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'seeds_original_seeder_id_fkey', 'seeds', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'seeds_original_seeder_id_fkey', 'seeds', 'users', ['original_seeder_id'], ['id'])
    ### end Alembic commands ###
