"""empty message

Revision ID: d579e2644764
Revises: 68b864673cd6
Create Date: 2016-10-25 20:17:18.771357

"""

# revision identifiers, used by Alembic.
revision = 'd579e2644764'
down_revision = '68b864673cd6'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('upvotes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'upvotes')
    ### end Alembic commands ###
