"""empty message

Revision ID: db98d862d089
Revises: e4a4a0834a16
Create Date: 2016-08-18 17:50:09.426654

"""

# revision identifiers, used by Alembic.
revision = 'db98d862d089'
down_revision = 'e4a4a0834a16'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circles', sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circles', 'point')
    ### end Alembic commands ###
